jupyterlab/jupyterlab-git

- README.md
Adding information about the summer team.
> Intial readme

- git_handler/hi/hi/__init__.py
- git_handler/hi/hi/handlers.py
- git_handler/hi/hi/static/one.js
- git_handler/hi/setup.py
git handler files (as jupiter notebook extension)
need to install handlers separately,
> handler folder

- jupyterlab_git/__init__.py
- jupyterlab_git/git.py
- jupyterlab_git/handlers.py
This pull request solves #109 #110
> PEP-8 Compatible

- src/components/branchHeader.tsx
- src/components/pastCommits.tsx
- src/components/statusFiles.tsx
- style/Images/add.svg
- style/Images/reset-white.svg
- style/Images/triangle-down-white.svg
- style/Images/triangle-down.svg
- style/Images/triangle-right-white.svg
- style/Images/triangle-right.svg
- style/index.css
- style/variables.css
Some more changes to the UI. More to come tomorrow!!
> UI design 2

- jupyterlab_git/git.py
- src/components/pastCommits.tsx
- src/git.ts
- style/index.css
Changed the filepath to filename in past commits files
> Filepath to filename change

- src/components/statusFiles.tsx
- style/Images/caretdownwhite.svg
- style/Images/caretrightwhite.svg
- style/index.css
- style/variables.css
Make caret icons for branch dropdown and for collapsible file browser items consistent with rest of JupyterLab
> New Caret Icons 

- LICENSE
Changed license to refer to "Project Jupyter Contributers".
> Update LICENSE - Fixes #156

- src/components/components.tsx
- Added basic style updates to error message when current folder is not a `git` repository.
- Updated error message to be more explanatory for a better experience.
> Improve error message

- src/components/GitPanel.tsx
- src/components/PathHeader.tsx
- src/componentsStyle/PathHeaderStyle.tsx
path header is now repo/branch
> path header style

- ROADMAP.md
The line items are broken down into 3 categories - CI/CD, Existing Features, and New Features. Each line item will have a corresponding issue in the repo.
> Add a roadmap document

- .travis.yml
- README.md
- tests/unit/test_handlers.py
* Add a single unit test using PyTest and run this using Travis.
* Also add a build badge in the README for the master branch
> Add initial Travis config & unit test

- package.json
> Add discovery metadata

- .travis.yml
- jest.config.js
- package.json
- setupJest.js
- test/test-components/BranchHeader.spec.ts
- tsconfig.json
- tslint.json
- yarn.lock
- `tslint.json` is adopted from https://github.com/jupyterlab/jupyterlab/blob/master/tslint.json
- Removed `rootDir` tag from `tsconfig.json` as it was affecting test discovery. 
-- Changing `rootDir` to “src/../“ or putting "test" directory inside "src" directory, allows test discovery.
-- There are many open issues related to this issue affecting test discovery.
--- https://github.com/Microsoft/nodejstools/issues/1949
--- https://github.com/Microsoft/nodejstools/issues/1243
> Add unit tests for Branch Header component

- jest.config.js
- package.json
Testing
```
→ yarn clean && yarn build && yarn test
yarn run v1.10.1
$ rimraf lib
✨  Done in 0.41s.
yarn run v1.10.1
$ tsc
✨  Done in 4.40s.
yarn run v1.10.1
$ jest
(node:62367) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.props.refresh is
not a function
(node:62367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
are not handled will terminate the Node.js process with a non-zero exit code.
(node:62367) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: this.props.refresh is
not a function
(node:62367) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: this.props.refresh is
not a function …
```
> Fix build failure #251

- package.json
- setup.py
> Release 0.5

- jupyterlab_git/git.py
- specification/Git_REST_API.md
- specification/Git_REST_API.yml
- src/components/PastCommitNode.tsx
- src/git.ts
- tests/test-components/PastCommitNode.spec.tsx
- tests/unit/test_branch.py
> Send full commit SHA1 for each branch

- README.md
> Update current list of maintainers

- CONTRIBUTING.md
This is a first go at addressing #319 by writing down the different processes for contribution
> First go at laying out processes for contribution

- tests/test-components/FileItem.spec.tsx
Addresses #337 
* Fix props
* Fix tslint
> Fix build failure: syntax issues in FileItem spec

- src/components/PathHeader.tsx
- src/gitPushPull.ts
* Show a spinner while the operation is in progress (Helps with large commits or slow remotes)
* Show a confirmation in the success case.
* Show error message in the failure case.
* Addresses #323
> Display push/pull progress and success.

- .travis.yml
- package.json
- tests/test-browser/chrome-test.js
- tests/test-browser/run_browser_test.py
- yarn.lock
```
→ python -m tests.test-browser.run_browser_test
[W 13:06:14.910 BrowserApp] Error loading server extension jupyter_nbextensions_configurator
Traceback (most recent call last):
File "/Users/neelamg/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1546, in init_server_extensions
mod = importlib.import_module(modulename)
File "/Users/neelamg/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 13:06:14.930 …
```
> Setup puppeteer and add basic browser test

- package.json
- setup.py
https://pypi.org/project/jupyterlab-git/#history
https://www.npmjs.com/package/@jupyterlab/git/v/0.6.0
Addresses #356
> Release 0.6.0

- .travis.yml
- postBuild
- setup.py
> Remove psutil dependency

- src/gitClone.ts
Update git clone placeholder text to illustrate integration works with any git host
> Update git clone placeholder text

- .travis.yml
- jupyterlab_git/git.py
- tests/test-browser/chrome-test.js
- tests/test-browser/run_browser_test.py
> Don't use f-strings

- jupyterlab_git/handlers.py
- specification/Git_REST_API.md
- specification/Git_REST_API.yml
- tests/unit/test_config.py
@jaipreet-s I'm sorry I was so sure unit tests have my back... So this fixes #387
> Fix identity error

- package.json
- setup.py
- style/diff.css
* Contains the changes for Identity feature and Visual Diff of Notebook files
* Synchronize versions of the server and frontend extension
* Add dependency on nbdime (There's no new release of nbdime yet so this declares a dependency via Git)
* Minor updates to the Diff button style to not make it look huge
> Release 0.8

- .github/issue_template.md
Fixes #396 and follow-up #397 discussion
Note: I'm ready to help more the management of this package, if you want. But my current rights are very basic.
> Create a template for issue

- .travis.yml
- README.md
- package.json
- yarn.lock
> Update documentation and dev depencies

- src/model.ts
- src/tokens.ts
> Reorganize model

- src/components/diff/PlainTextDiff.tsx
Fix error reported in #484 for plain text file
> Correct bug on plain text diff

- src/components/PathHeader.tsx
This PR
-   fixes a missing title attribute for one of the path header icons.
> Fix missing title

- .github/issue_template.md
- README.md
- Mention Troubleshooting section in issue template
- Add missing `install` in README command
- prettier README
> Mention Troubleshooting section in issue template

- jupyterlab_git/git.py
- jupyterlab_git/tests/test_config.py
> Fix multiline Git options interpretation

- jupyterlab_git/handlers.py
> Format root directory folder as posix

- README.md
- binder/environment.yml
- binder/postBuild
> Add binder configuration

- src/style/PastCommitNodeStyle.ts
This PR fixes https://github.com/jupyterlab/jupyterlab-git/issues/546
> fix flex-shrink issue in safari

- .gitignore
- README.md
- src/components/Toolbar.tsx
- src/widgets/gitClone.tsx
Changes are to handle 
- In Push/Pull Credential dialog box, incorrect warning message is coming
- For Git clone, if an incorrect url is entered, Jupyter Lab freezes
- If exisiting repo is attempted for a Git clone again, Jupyter Lab freezes
- In Git credentials dialog box, if incorrect username/password is entered, Jupyter Lab freezes
> Updating Exception Handling Scenarios

- jupyterlab_git/git.py
- jupyterlab_git/tests/test_status.py
> Fix status error on empty string

- jupyterlab_git/_version.py
- package.json
bumps version in _version.py and package.json
> bump master to v0.20.0

- binder/environment.yml
> Correct JupyterLab version in binder environment

- schema/plugin.json
> Correct icon for Git settings in JLab2

- src/model.ts
> Test for `response.ok` not `status === 200`

- .github/issue_template.md
Fixes #673
@ianhi could you review this one please?
> Add Git version and OS to issue template

- src/components/Toolbar.tsx
- src/gitMenuCommands.ts
- src/index.ts
- src/tokens.ts
- tests/test-components/Toolbar.spec.tsx
> Backport PR #699 on branch 0.11.x

- jupyterlab_git/tests/test_ignore.py
- src/model.ts
Add unit tests for ignore feature
> Backport of #717  Add unit tests for ignore feature

- src/components/NewBranchDialog.tsx
**current behavior**:
**new behavior**:
> Have icon class influenced by selection in New Branch Dialog

- src/style/StatusWidget.ts
Correct status widget text style to match Python kernel status by respecting the theme.
> Theme status widget text

- jupyterlab_git/handlers.py
> Set status 500 when git commands fail

- src/model.ts
- src/tokens.ts
- tests/model.spec.tsx
- tests/plugin.spec.ts
Fixes #809 
It corrects `showPrefix` also
> Fixes top repository refresh

- jupyterlab_git/git.py
- jupyterlab_git/handlers.py
- package.json
- src/components/BranchMenu.tsx
- src/components/TagMenu.tsx
- src/model.ts
- src/style/BranchMenu.ts
- src/style/icons.ts
- src/tokens.ts
- style/icons/trash.svg
- tests/test-components/BranchMenu.spec.tsx
> Delete local branch 

- jupyterlab_git/git.py
- jupyterlab_git/tests/test_branch.py
Fix for issue https://github.com/jupyterlab/jupyterlab-git/issues/848
> Bug Fix: Replace lstrip with replace function

- src/commandsAndMenu.tsx
- src/components/Feedback.tsx
- src/components/FileList.tsx
- src/components/GitPanel.tsx
- src/components/TagMenu.tsx
- src/components/diff/Diff.tsx
- src/components/diff/NBDiffHeader.tsx
- src/components/diff/NbDiff.tsx
- src/components/diff/PlainTextDiff.tsx
- src/components/diff/mergeview.ts
- src/logger.ts
- src/model.ts
- src/utils.ts
- src/widgets/StatusWidget.ts
- src/widgets/gitClone.tsx
This will ease review PR by removing warnings noise
> Remove eslint warnings

- README.md
https://github.com/jupyterlab/jupyterlab-git/pull/891#discussion_r588900207
@fcollonval @EnisBerk is that what was intended?
> Fill out details in troubleshooting

- README.md
Use raw GitHub URL to reference the image in the README
> Fixes #762

- src/index.ts
- style/base.css
- style/diff-nb.css
- style/index.css
If JupyterLab is not built to integrate nbdime extension, nbdime styles are not loaded and the notebook diff is not pretty.
> nbdime styles are not imported

- src/commandsAndMenu.tsx
https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/terminal-extension/src/index.ts#L98
> Disable 'Open Git Repository in Terminal' if terminals are not available

- jupyterlab_git/git.py
get_content needs to adapt to asynchronous contentsmanager
see more from https://github.com/jupyter/nbdime/issues/595
> Compatible with asynchronous contentsmanager

- package.json
- setup.py
- yarn.lock
To pick up the fixes for #936 from https://github.com/jupyter/nbdime/pull/593. They yarn lock update picked up a few other minor updates, I hope it's ok.
> Bump nbdime version

- src/index.ts
- tests/commands.spec.tsx
- tests/test-components/BranchMenu.spec.tsx
- tests/test-components/CommitBox.spec.tsx
- tests/test-components/FileItem.spec.tsx
- tests/test-components/GitPanel.spec.tsx
- tests/test-components/Toolbar.spec.tsx
- ~~The translation strings are not all captured by introspection~~ => cover by https://github.com/jupyterlab/jupyterlab-translate/pull/6
- Update the domain name to the normalized version
> Fix translation

- src/components/Toolbar.tsx
> Fix test against null (empty string is valid)

- src/components/NewBranchDialog.tsx
Fix selection in new branch dialog (the current selected branch was not highlighted as appropriate)
Fix string to be translated not captured
Add description for _master_ | _main_ branch
> Fix selection in new branch dialog

- .github/workflows/binder-on-pr.yaml
- src/commandsAndMenu.tsx
- src/index.ts
- tests/plugin.spec.ts
This is not handling a hypothetical filebrowser widget change
> Get filebrowser from current tracked widget

- package.json
- src/commandsAndMenu.tsx
- src/components/StatusWidget.tsx
- src/index.ts
- src/model.ts
- src/widgets/GitWidget.tsx
- yarn.lock
Use the filebrowser tracker everywhere
> Improve signal lifecycle

- schema/plugin.json
> Doubling click → double click

- jest.config.js
- src/commandsAndMenu.tsx
- src/model.ts
- tests/model.spec.tsx
No Git history for selected file - Fixes #1024
Don't display context menu items if the current folder is not a Git repository.
> Fix Git History

- package.json
- setup.py
> Bump to 0.33.0

- jest.config.js
- src/commandsAndMenu.tsx
- src/model.ts
- tests/model.spec.tsx
* No Git history for selected file
Fixes #1024
* No context menu item if not in a repository
> Backport PR #1028 on branch 0.32.x (Fix Git History)

- src/style/BranchMenu.ts
- src/style/FileItemStyle.ts
- src/style/SinglePastCommitInfo.ts
This PR resolves #1060
Adds userSelect style to gileitem and branchmenu.
> [UI] userSelect css bug 

- jupyterlab_git/git.py
- jupyterlab_git/tests/test_branch.py
> Fixed error switching remote branch, fixes #741

- src/components/SinglePastCommitInfo.tsx
> Fix typo in SinglePastCommitInfo.tsx

- src/components/NewBranchDialog.tsx
> New branch is not "based on" selection

- jupyterlab_git/git.py
- jupyterlab_git/tests/samples/ipynb_base.json
- jupyterlab_git/tests/samples/ipynb_nbdiff.json
- jupyterlab_git/tests/samples/ipynb_remote.json
- jupyterlab_git/tests/test_handlers.py
- jupyterlab_git/tests/test_jupytext.py
- setup.cfg
This force to request the file content of the working files as raw string (not letting the content manager guessing if it may be a notebook file).
Fixes #970
> Fix diff file broken for working file when Jupytext is installed

- src/components/CommitBox.tsx
- src/components/CommitComparisonBox.tsx
- src/components/CommitDiff.tsx
- src/components/CommitMessage.tsx
- src/components/GitPanel.tsx
- src/components/HistorySideBar.tsx
- src/components/PastCommitNode.tsx
- src/components/SinglePastCommitInfo.tsx
- src/style/ActionButtonStyle.ts
- src/style/CommitBox.ts
- src/style/CommitComparisonBox.ts
- src/style/FileItemStyle.ts
- src/style/GitPanel.ts
- src/style/GitStageStyle.ts
- src/style/HistorySideBarStyle.ts
- src/style/PastCommitNode.ts
- src/style/SinglePastCommitInfo.ts
- src/style/Toolbar.ts
- style/variables.css
- tests/test-components/CommitBox.spec.tsx
- tests/test-components/PastCommitNode.spec.tsx
- ui-tests/package.json
- ui-tests/tests/commit-diff.spec.ts
improve the styles and the code for the commit box and the commit diff
> Improve commit box and commit diff

- src/components/CommitBox.tsx
- src/components/GitPanel.tsx
- src/model.ts
- src/tokens.ts
- tests/test-components/CommitBox.spec.tsx
- tests/test-components/GitPanel.spec.tsx
> Better handle case of unsaved changes

- README.md
- src/widgets/GitCloneForm.ts
> fixes #1121 by trimming whitespace from user input of clone URI path

- jupyterlab_git/git.py
> avoid crashing if cell id doesnt exist when diffing notebooks

- jupyterlab_git/handlers.py
Apply same logic as https://github.com/jupyter-server/jupyter_server/blob/15310fd760d21be84a1509c0f875970c0c0faaef/jupyter_server/base/handlers.py#L708
> Raise error instead of set status

- src/index.ts
> fix: export logger instance for external use

- jupyterlab_git/git.py
- jupyterlab_git/handlers.py
- jupyterlab_git/tests/test_clone.py
- src/cloneCommand.ts
- src/commandsAndMenu.tsx
- src/model.ts
- src/tokens.ts
- src/widgets/GitCloneForm.ts
- style/credentials-box.css
Resolves https://github.com/jupyterlab/jupyterlab-git/issues/856
> Support downloading a git repository snapshot

- .github/workflows/build.yml
- conftest.py
- jupyterlab_git/handlers.py
- jupyterlab_git/tests/test_hybridcontents.py
- setup.cfg
Fix handler
Upgrade to pytest-jupyter
Fix CI
> Add support for Jupyter Server 2

- README.md
> Add constrain in install instructions

- src/commandsAndMenu.tsx
- src/model.ts
> Fix testing `pathRepository` for `null`

- .github/workflows/update-integration-tests.yml
- yarn.lock
Update snapshot workflow update from the latest extension-template
> Update snapshot workflow update from template

- .github/workflows/prep-release.yml
- .github/workflows/publish-release.yml
To make use of the GitHub app for releasing.
> Update the releaser workflows
