setup.py
I got 
```
> jupyter serverextension enable --py jupyterlab_git
Traceback (most recent call last):
File "/home/andy/anaconda3/envs/jupyterlab/bin/jupyter-serverextension", line 6, in <module>
sys.exit(notebook.serverextensions.main())
File "/home/andy/anaconda3/envs/jupyterlab/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/home/andy/anaconda3/envs/jupyterlab/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
app.start()
File "/home/andy/anaconda3/envs/jupyterlab/lib/python3.6/site-packages/notebook/serverextensions.py", line 293, in start
super(ServerExtensionApp, self).start()
File …
```
=> Add psutil to install_requires

jupyterlab_git/__init__.py, jupyterlab_git/git.py
Should resolve #179
With this PR, the git tab seems to be working when Jupyter Lab is launched using the `--notebook-dir` option:
```bash
jupyter lab --notebook-dir=<path-to-a-git-repo>
```
=> Change working directory for git to be the server root path

README.md
I think it is important to add a team section to the README, similar to what we have done for the main JupyterLab repo. AWS folks, feel free to submit a PR adding your name, affiliation and areas of responsibility.
=> Add team section to README

src/components/FileItem.tsx, src/components/FileList.tsx, src/components/GitStage.tsx
This change includes a modal confirmation before discarding all or single file changes and Error message when discard operation fails.
It fixes #226
=> Add friction to discard action for all changes and single file changes

src/gitClone.ts
Previously, the onClick modal would still fire even if the button was disabled. Also, the tooltip wouldn't reflect why the button is disabled. This change fixes both of those.
#253 
cc: @neelamgehlot  FYI
=> Disable modal and enable a tooltip when clone button is disabled

src/gitMenuCommands.ts
Fixes #263 by putting path in double quotes which would escape any special character.
```
directory .  ( with  )  * spacial ? chars
directory with    irregular   spaces
directory-with-"double" quotes and space
directory-with-""double" quotes and space
directory-with-'single' quote and space
```
=> Fixes #263 by putting path in double quotes

package.json, setup.py
https://pypi.org/project/jupyterlab-git/0.4.4/#history
https://www.npmjs.com/package/@jupyterlab/git
I don't think there is a way to create tags via PR.  If so, I can push a `v0.4.4` tag to the repo after this is merged.
Related to #262
=> Release 0.4.4

jest.config.js, package.json, setupJest.js, src/components/BranchHeader.tsx, src/components/GitPanel.tsx, src/components/HistorySideBar.tsx, src/components/PastCommitNode.tsx, src/components/PastCommits.tsx, src/components/SinglePastCommitInfo.tsx, src/componentsStyle/BranchHeaderStyle.tsx, src/componentsStyle/GitPanelStyle.tsx, src/componentsStyle/HistorySideBarStyle.tsx, src/componentsStyle/PastCommitNodeStyle.tsx, src/componentsStyle/PathHeaderStyle.tsx, src/componentsStyle/SinglePastCommitInfoStyle.tsx, src/git.ts, tests/test-components/BranchHeader.spec.ts, tests/test-components/HistorySideBar.spec.tsx, tests/test-components/PastCommitNode.spec.tsx, yarn.lock
This addresses #245 by making a seperate history tab.
It implements all the features requested by #245 except for the graphical branch view on the left hand side. 
It also is not a pixel perfect translation of the mockups. I reused as much of the existing styles and components as possible. As a result, there should likely be some cleanup after this to reflect the component name updates. (i.e. `HistorySideBar` is no longer a side bar).
=> Improve history overview

jupyterlab_git/git.py, jupyterlab_git/handlers.py, tests/unit/test_branch.py
When there are no tags, `git describe` returns `fatal: No names found, cannot describe anything`. This fails the entire `/git/all_history` API call and we fail to identify the Git repo completely.
This commit doesn't fail in this case but returns an empty list of tags and also uses the `--tag` option which returns non-annotated tags as well.
---
Unit Tested: pytest test/
Tested via local JupyterLab installation and with a fresh GitLab repo
---
=>  Fix git repo determination when there are no tags

package.json, yarn.lock
The current `package.json` does not allow good integration with JupyterLab.
Changes proposed:
- Use the same version of `react` and `react-dom` as the one of JupyterLab. The current config results in two versions of react being bundled by webpack.
- `tslint` should be a `devDependency` not a `dependency`
- `@types/react` is unfortunately a dependency of `@jupyterlab/apputils` (see https://github.com/jupyterlab/jupyterlab/pull/4386 and https://github.com/jupyterlab/jupyterlab/pull/5268#discussion_r215307531), to ease contribution from new developers `resolutions` key should be added in the configuration file (see https://github.com/jupyterlab/jupyterlab/issues/5456#issuecomment-427881191).
=> Improve package.json

src/components/GitPanel.tsx, src/components/GitWidget.tsx, src/components/HistorySideBar.tsx, src/components/PastCommitNode.tsx, src/components/PastCommits.tsx, src/components/SinglePastCommitInfo.tsx, src/git.ts, src/index.ts
- Rename `register_diff_provider` --> `registerDiffProvider`.
- Ensure `IGitExtension` is listed in `provides` of plugin.
- Re-order declarations to enable previous point (and help reading of code).
TODO: Still untested. I'll try to develop against this locally with nbdime and see if I can get this to work. If and when, I'll ping this PR again!
Fixes #192.
=> Rename extension API method, provide interface

jupyterlab_git/git.py
This fixes unstaging deleted files and closes https://github.com/jupyterlab/jupyterlab-git/issues/294. 
If we don't specify the `--`, then I get this error:
```
fatal: ambiguous argument 'setupJest.js': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
=> Fix unstaging deleted files

src/components/BranchHeader.tsx, src/components/FileItem.tsx, src/components/FileList.tsx, src/components/GitPanel.tsx, src/components/GitStage.tsx, src/components/HistorySideBar.tsx, src/components/PastCommitNode.tsx, src/components/PastCommits.tsx, src/components/PathHeader.tsx, src/components/SinglePastCommitInfo.tsx, src/componentsStyle/BranchHeaderStyle.tsx, src/componentsStyle/FileListStyle.tsx, src/componentsStyle/GitStageStyle.tsx, src/componentsStyle/PastCommitNodeStyle.tsx, src/componentsStyle/PathHeaderStyle.tsx, src/componentsStyle/SinglePastCommitInfoStyle.tsx, style/variables.css, tests/test-components/BranchHeader.spec.tsx, tests/test-components/HistorySideBar.spec.tsx, tests/test-components/PastCommitNode.spec.tsx, tests/test-components/PathHeader.spec.tsx
This closes #307 by improving the appearance of in the dark theme. 
It also [switches from detecting the with JS to CSS](https://github.com/jupyterlab/jupyterlab-git/commit/0c340ab58376f7688430cf397c2063d45dc1a771).
=> Fix dark theme appearance

src/git.ts, src/gitClone.ts, src/index.ts
Not all errors are "auto-fixable" but taking some incremental steps towards fixing them in gitClone.ts and index.ts
Ideally, we should be in a state where tslint erors should fail the buil.d
=> Fix some tslint errors

src/components/FileItem.tsx, tests/test-components/FileItem.spec.tsx
This fixes #327 by showing a the full file path on hover over a file name:
=> Add full file path to tooltip over file

.travis.yml, package.json, src/components/BranchHeader.tsx, src/components/FileList.tsx, src/components/GitPanel.tsx, src/components/GitStage.tsx, src/components/GitWidget.tsx, src/components/HistorySideBar.tsx, src/components/PastCommitNode.tsx, src/components/PathHeader.tsx, src/components/ResetDeleteSingleCommit.tsx, src/components/SinglePastCommitInfo.tsx, src/componentsStyle/BranchHeaderStyle.tsx, src/componentsStyle/GitPanelStyle.tsx, src/componentsStyle/HistorySideBarStyle.tsx, src/componentsStyle/PastCommitNodeStyle.tsx, src/componentsStyle/PathHeaderStyle.tsx, src/componentsStyle/SinglePastCommitInfoStyle.tsx, src/git.ts, src/gitClone.ts, src/gitMenuCommands.ts, src/index.ts, tests/test-components/HistorySideBar.spec.tsx, tests/test-components/PastCommitNode.spec.tsx, tests/test-components/PathHeader.spec.tsx, tsconfig.json, tslint.json, yarn.lock
* Make tslint rules compatible with prettier
* run linting in CI
* run linting on commit on touched files
* integrate tslint into typescript compilation pipeline so that errors appear in vscode (after changing typescript interpreter to use workspace one)
* fix all other linting errors manually
=> Stricter lint

jupyterlab_git/git.py, tests/unit/test_pushpull.py
A previous commit, https://github.com/jupyterlab/jupyterlab-git/pull/344, started passing env variables as a parameter.
This broke the behaviour of "shell=True" which expects a string and all the push/pull commands would fail.
* Manually tested via JupyterLab as well as the REST API to check that push/pull is working successfully
=> Fix push/pull to not use shell=True

jupyterlab_git/git.py, jupyterlab_git/handlers.py, tests/unit/test_diff.py
This change adds a endpoint to the server to list the files changed in the working tree, staging area, between two commits, or in a single commit.
This will be used by the "DiffComponent" to call the sub-components based on the file extension, i.e, all ipynb files will be delegated to the NBDiffComponent and all other files will be delegated to the PlainTextDiffComponent.
=> Server API to list changed files in Git

jupyterlab_git/git.py, tests/unit/test_clone.py
Related to
* Similar fix made for push/pull https://github.com/jupyterlab/jupyterlab-git/pull/362
* Related issue https://github.com/jupyterlab/jupyterlab-git/pull/344 #367 
Tested by running locally and doing a "clone" from the UI
=> Update clone to not use shell=True

src/gitClone.ts
Upon path change, disableIfInGitDirectory unnecessarily invokes all_history which ends up running 4 git commands instead of 1, just to check if the new path is a git repo.
This results in performance impact in some configurations (as "git status" goes over the whole file sub tree).
all_history verifies first show_top_level's result and only then proceeds to the other commands, so it should be enough in this case.
Addresses #349
=> Minimize git access upon changed path

.travis.yml, jupyterlab_git/git.py, jupyterlab_git/handlers.py, specification/Git_REST_API.md, specification/Git_REST_API.yml, src/components/BranchHeader.tsx, src/components/GitPanel.tsx, src/components/PathHeader.tsx, src/git.ts, src/index.ts, src/widgets/AuthorBox.ts, src/widgets/gitClone.ts, src/widgets/gitPushPull.ts, tests/test-browser/chrome-test.js, tests/test-browser/run_browser_test.py, tests/test-components/BranchHeader.spec.tsx, tests/unit/test_config.py
Fixes #351 and will imply simplification in #345.
If the user has no `user.name` and no `user.email` defined in Git global configuration, the GitPanel will be replaced by a warning and a button prompting the user for a name and an email.
If the user provides them, they will be added as global configuration options in git. Then the extension will behave as previously.
Note;
* The email is not verified to be a valid email string
* If the user removes his identity after opening JupyterLab (very unlikely), the extension is never checking again if an identity is set.
None
=> Identity feature

jupyterlab_git/handlers.py, src/components/FileItem.tsx, src/components/FileList.tsx, src/components/SinglePastCommitInfo.tsx, src/components/diff/Diff.tsx, src/components/diff/DiffWidget.tsx, src/git.ts, tests/test-components/DiffWidget.spec.tsx, tests/test-components/NBDiff.spec.tsx, tests/test-components/testutils.ts
Closes #391 
This change adds a endpoint in the server extension to get the `server_root` and then resolve the path of the file relative to `server_root` before calling the nbdime API
=> Use the path relative to server root for diffs

jupyterlab_git/git.py
This pull request is to be defensive and add a little flexibility when checking for exact error messages from the output of `git` commands.
At Twitter, we have a custom fork of Git that apparently has the `n` letter capitalized for the `git rev-parse --abbrev-ref branch@{upstream}` scenario which was breaking the `GitPanel` component ultimately resulting in an inability to create new branches. 
This change would help us maintain a dependency with this upstream version rather than a custom fork and is backwards compatible.
Thanks!
=> Lowercase Git error messages before checking substring existence

jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py
Add handling for corner case when remote branch have been deleted while local branch still persists. To reproduce existing bug:
```
git branch exist-on-local-but-deleted-on-remote-branch
git push --set-upstream origin exist-on-local-but-deleted-on-remote-branch
git push --delete origin exist-on-local-but-deleted-on-remote-branch
```
this is caused by calling
`git rev-parse --abbrev-ref exist-on-local-but-deleted-on-remote-branch@{upstream}`
which returns
```
fatal: ambiguous argument 'exist-on-local-but-deleted-on-remote-branch@{upstream}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
this small MR address the issue by addling the handle for this error message, which should …
=> gitApi: add corner case handling for deleted remote branches

jupyterlab_git/git.py, jupyterlab_git/tests/test_detailed_log.py
Files with spaces weren't being recognized because of a split in `Git.detailed_logs` that was splitting too much, see #427
The `Git.detailed_logs` function was also missing tests so I added some to validate my fix. I used the same test structure as what I found in `test_branch.py`.
I validated this locally too and it works as expected :+1:
=> Fix filename split in detailed log (#427)

.travis.yml, MANIFEST.in, jupyterlab_git/_version.py, jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_handlers.py, package.json, schema/plugin.json, src/components/GitPanel.tsx, src/components/GitWidget.tsx, src/git.ts, src/index.ts
This PR adds a schema file for user settings for this extension. `jupyterlab-git` now has a section in the Advanced Settings Editor that you can access via the Settings menu. I've also added a simple `historyCount` setting to get the git settings started. It controls how many logs are visible in the history tab.
=> Adds user setings: historyCount controls number of logs shown

style/diff.css, style/index.css, style/variables.css
The CSS imports in `index.ts` were (rightfully) dropped in #426. Unfortunately, `diff.css` is now not getting imported anywhere, so we're missing styling for the nbdime diff. This PR fixes that by importing `diff.css` in `index.css`
=> ensured that the styling in diff.css gets imported into the bundle

.travis.yml
This fixes the bug appearing in the scheduled master check: https://travis-ci.org/jupyterlab/jupyterlab-git/builds/604902811?utm_medium=notification&utm_source=github_status
=> Fix usage of old node in CI

jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py, jupyterlab_git/tests/test_handlers.py
As I pointed out in #432, the `/git/all_history` API, and the GitPanel refresh that uses it, has some serious performance problems, especially in repos with many branches/tags. This is a serious usability issue for `jupyerlab-git`, since GitPanel refresh is fired whenever a user tries to open a different repo in the sidebar, including at startup.
This PR fixes the issue by refactoring `Git.branch` to require far fewer subprocess calls to fetch almost the same data. The one external change is that `Git.branch` no longer fetches a branch's "tag", which was very slow. The "tag" in this case is the most recent tag made before the leading commit of a particular branch, which is not really a standard git concept. More importantly, we aren't actually using the branch "tag" data anywhere, so it's …
=> Greatly improve performance of GitPanel refresh by streamlining Git.branch

jupyterlab_git/git.py, jupyterlab_git/handlers.py, src/components/FileList.tsx, src/model.ts
Basically, we doing an inappropriate `git add -A` where we should have been doing `git add -u`. This has been fixed.
In various places in the code we refer to the 3 categories of files that git pays attention to as untracked, unstaged, and staged. We should try to be as consistent about these names throughout the program as we can be (eg, we should probably(?) change the text header over the middle file list from `Changed` -> `Unstaged`). Being consistent will help us to avoid this kind of unexpected behavior in the future.
=> fixes #442: addAllUnstagedFiles now has the correct behavior

jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py
Currently, checking out a remote branch results in a detached branch.
The fix included in this branch does the following:
* it provides a new method to get the branch reference:
_get_branch_reference(self, branchname, current_path)
* it changes the behavior of the checkout_branch(...) method so that the '--track' parameter is passed during remote branches checkout.
Current checkout behavior is unchanged for local branch checkouts and also in case of error.
=> Fix remote checkout

babel.config.js, jest.config.js, jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py, schema/plugin.json, src/components/CommitBox.tsx, src/components/FileItem.tsx, src/components/FileItemSimple.tsx, src/components/FileList.tsx, src/components/GitPanel.tsx, src/components/GitStageSimple.tsx, src/components/PastCommitNode.tsx, src/gitMenuCommands.ts, src/index.ts, src/model.ts, src/style/FileItemSimpleStyle.ts, src/tokens.ts, src/utils.ts, tests/GitExtension.spec.tsx, tests/test-components/CommitBox.spec.tsx, tests/test-components/FileList.spec.tsx
This is a resumption of the work from #437 following the major refactor that was done in #438. I've cherry picked various lines from #437 to get this started. Here's the info from the old PR:
>For people who haven't used any VCS before, `git` can prove to be somewhat overwhelming. In particular, the untracked/unstaged/staged concept can seem very foreign to someone who up until now has never done any kind of "commit" more complicated than saving a file to disk. For that reason I think it would be idea to have an option to switch the staging UI to a "simplified" mode. As a model, I'm thinking along the lines of the UI in the Github desktop app:
>It would simply show which files have changed, rather than splitting them into categories. When the commit button is pushed, all changed files …
=> Simplify the staging UI to make it easier for git beginners

jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py
Fixes #460
Simple staging was broken for newly init-ed repos. This turns out to have been due to broken lookup of branch names for the case of repos with no commits. This PR fixes the general issue by changing around the internals of the `branch_heads` and `get_current_branch` functions in `git.py` in the serverextension to be more robust in these situations.
=> Fixes #460: better handling of branch edge cases

README.md
This PR
-   adds a demo notebook.
Having a demo notebook in the plugin repository is useful for two reasons:
1.  when opening the associated Binder, a user can immediately play around with a sample notebook having varied outputs, without needing to create one herself. This is particularly useful when testing the NBDime diffs.
2.  when performing local development, having a demo notebook is useful when testing out new and/or modified features.
The included demo notebook is based on a similar notebook from JupyterLab core.
=> Add demo notebook

schema/plugin.json, src/index.ts, src/model.ts
This PR resolves https://github.com/jupyterlab/jupyterlab-git/issues/454 by
-   reducing the refresh interval to create a more responsive user experience. Previously, if a file change was made outside of the lab environment, it could take up to 10 seconds for the Git extension to register that a change had been made. After experimenting with different durations, I settled on a (maximum) duration of 3 seconds. In my experience, once I had to wait longer, I immediately began wondering if something was wrong. Maybe others are more patient.
-   exposing a `refreshInterval` configurable setting. This should allow users (and organizations) to adjust the polling behavior according to taste and desired performance profiles.
-   adding logic for listening to `fileChanged` events emitted by the …
=> Update refresh interval

jupyterlab_git/git.py
followup #448
Changes made in #448 allow the frontend/backend to git add more than one file at a time with a single `add` cmd. This PR fixes a related backend issue with parsing multiple files when generating the cmd.
Also fixes committing more than one file at a time in simple staging mode
=> followup #448: fix git add multiple files

src/components/BranchHeader.tsx, src/components/GitPanel.tsx
followup #450
Currently, if `"disableBranchWithChanges": true` is in settings, branch ops are disabled completely in all cases. This PR restores the old "disable when there are changes" behavior when the setting is `true`
=> followup #450: fixes behavior when `"disableBranchWithChanges": true`

jupyterlab_git/_version.py, package.json, release.py
This PR bumps the Python and npm packages to `0.10.0` for the dev build, now that `0.9.0` has been released. If we do need to do any patch releases before `0.10.0` is released, we can use a backport branch strategy similar to what jlab core does.
The PR also contains the final tweaks to the release system that I had to make while doing the `0.9.0` release
=> bump to `0.10.0` for dev branch; final `0.9.0` release system fixes

src/components/SinglePastCommitInfo.tsx, src/style/SinglePastCommitInfoStyle.ts
This PR
-   sets the fill color of the insertion and deletion icons in the Git history panel, thus providing a color indication, similar to Git terminal output, as to insertion and deletion statistics.
Before:
After:
=> Color insertion and deletion icons

src/style/HistorySideBarStyle.ts
This PR resolves #481 by
-   adjusting the bottom panel margin thus ensuring that (a) the panel content extends to the bottom of the Git panel and (b) any side scrollbars are flush against the bottom of the Git panel.
New behavior:
=> Fixes #481: Adjusts bottom panel margin

src/style/PathHeaderStyle.ts
Currently, icon margins simply expand and contract as the Git side panel expands and contracts, leading to (arguably) unnatural icon alignment. This PR changes to fixed icon margins and ensures that the icons remain right-aligned as the side panel is resized.
Before:
After:
=> Adjust icon spacing in path header component

src/style/BranchHeaderStyle.ts
This PR
-   adjusts branch dropdown item alignment.
Currently, branch dropdown items are center aligned which is poor for readability, as one must constantly reset to a new visual alignment position before reading the next list item.
Before:
After:
=> Adjust branch dropdown alignment

package.json, src/components/CommitBox.tsx, src/components/FileList.tsx, src/style/BranchHeaderStyle.ts, src/style/GitStageStyle.ts, src/style/GitWidgetStyle.ts, tests/test-components/CommitBox.spec.tsx, yarn.lock
fixes #225
supercedes #462
This replaces the current `textarea` that we use for the commit message with a `TextareaAutosize`, which is a drop-in replacement that autoresizes with the number of lines in the current input text. The `react-textarea-autosize` that provides this is minimal in size, and adds no extra deps beyond itself.
This PR will also carry over some the styling from #462 in order to make the resizable text input look nice next to the giant commit check mark button.
=> resizable commit message input box

src/components/SinglePastCommitInfo.tsx
This PR
-   sets `title` attributes for past commit info buttons, thus enabling native support for tooltips. Currently, if you hover over the buttons, no contextual information regarding button behavior is displayed.
=> Set title attributes to support tooltip info

src/gitMenuCommands.ts, src/model.ts
Fix #494 
API change
This implies removing `GitExtension.performDiff` method - method unused.
=> Remove the `cmd` argument in open terminal

jupyterlab_git/__init__.py
With this PR, the output of `jupyter serverextension list` will now correctly show the version of `jupyterlab-git`:
```
jupyterlab_git  enabled
- Validating...
jupyterlab_git 0.10.0 OK
```
=> fixes display of version in `jupyter serverextension list` ouput

src/components/diff/PlainTextDiff.tsx
The plain text diff viewer is injected in the DOM by providing the function with a HTML node. Before this PR, the node was found by using a (hopefully) unique HTML id. But this is not a robust solution.
This PR uses [React reference](https://reactjs.org/docs/refs-and-the-dom.html) instead; mechanism recommended for such case.
=> Use React.RefObject instead of id for plain text diff

src/components/BranchHeader.tsx
This PR
-   switches the tab order in the Git panel.
-   aligns the UI more closely with GitHub desktop.
-   works for both default and simplified staging.
Proposed change:
GitHub desktop:
=> Switch branch header tab order

jupyterlab_git/git.py
Explicitly list all untracked files instead of the containing folder if none of it's files are tracked.
=> List all untracked files

jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_remote.py, src/gitMenuCommands.ts, src/index.ts, src/model.ts, src/tokens.ts, tests/commands.spec.tsx
To start a respository with a remote from scratch, the extension is missing a command to add a remote repository. This PR fix that usage.
=> Add remote command

jupyterlab_git/handlers.py
fix #526, supercede #527
This is a replacement for #527, where @fcollonval said:
> This fixes the security hole discovered thanks to #526
> 
> When adding the decorator `@tornado.web.authenticated` to the handlers, they returned the following message instead of the valid answer:
> 
> ```
> {"message": "Forbidden", "reason": null}
> ```
=> add @web.authenticated to all handlers

README.md, jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_clone.py, jupyterlab_git/tests/test_pushpull.py, schema/plugin.json, src/model.ts, src/tokens.ts
Currently, the extension does not provide a means for easily resolving merge conflicts. When the extension pulls changes from a remote repository branch, if a conflict exists, the extension displays an error dialog (without an actual error message!), claiming that the `pull` failed; however, changes are still merged. A user must manually go through the changed files and resolve conflicts by modifying the source. Especially, for those unfamiliar with Git, this is error prone and a potentially frustrating experience.
This PR
-   adds a new setting: `cancelPullMergeConflict`. This setting is geared toward users who have limited Git experience, thus building on the "simple Git" concept. The main purpose of this setting is to guard against dirtying a user's working tree when conflicts with a …
=> Add setting support for canceling a pull if merge conflict

setup.py
The latest nbdime release is not compatible with JupyterLab 1.x, this PR pin to a nbdime release that is compatible with JupyterLab 1.x
=> Pin nbdime release compatible with JLab 1.x

package.json, yarn.lock
Fixes security alert: https://github.com/jupyterlab/jupyterlab-git/network/alert/yarn.lock/minimist/closed
The only real issue is that our sub-dep `extract-zip` has a hard pin on `mkdirp@0.5.1`, which in turn depends on a too-old version of `minimist`. This PR forces a minor version bump of that sub-sub dependecy to `mkdirp@^0.5.3`, and re-resolves some related stuff in yarn.lock
=> force some resolutions to bump `minimist` dependencies to at least 1.2.5

yarn.lock
Followup #562
Finishes fixing security alert https://app.snyk.io/vuln/SNYK-JS-ACORN-559469.
Just needed a re-resolve of `acorn@^6.0.1` in our yarn.lock
=> reresolve acorn@^6.0.1 to 6.4.1 in yarn.lock to finish fixing security alert

jupyterlab_git/git.py, jupyterlab_git/tests/test_detailed_log.py, jupyterlab_git/tests/test_diff.py, jupyterlab_git/tests/test_status.py
This encodes the filenames from `git status` to utf-8. With this change the filenames are properly displayed in the UI and git commands such as add, and push still function as expected as git can accept filenames in utf-8 encoding because "Git is to some extent character encoding agnostic." see: https://git-scm.com/docs/git-commit/2.13.4#_discussion
Fixes https://github.com/jupyterlab/jupyterlab-git/issues/543 and https://github.com/jupyterlab/jupyterlab-git/pull/545
<details><summary>gif of this working</summary>
</details>
=> Allow filenames with non-ascii characters

src/model.ts
When, for some reason, the jupyterlab_git jupyter server_extension
is not installed or available the user experience was just receiving a
json response error message. 
This pr extends the code around the first invocation to the backend
api and add better error handling around 404 errors to provide a better
user experience.
=> Display message when server extension unavailable

jupyterlab_git/git.py, src/model.ts
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/552
These buttons:
currently fail to add any files, and `add_all_untracked` doesn't produce and error message because of how it fails.
Change the key in the dictionary returned by `add_all_unstaged` and make `add_all_untracked` no longer require an interactive bash shell that doesn't work with current `execute` function.
=> Fix add_all_untracked and add_all_unstaged

.travis.yml, src/components/SinglePastCommitInfo.tsx, src/style/ActionButtonStyle.ts, src/style/SinglePastCommitInfo.ts
In the PR https://github.com/jupyterlab/jupyterlab-git/pull/521/files#diff-2161a1eeaacb5d5f156905ee326dd170 I unfortunately invert the icon for reverting to and discarding an past commit. This fixes it.
Moreover I added an effect (scale up) on `ActionButton` to provide a visual feedback to the user when it click on it.
=> Style improvement and fix

jupyterlab_git/git.py, jupyterlab_git/tests/test_detailed_log.py, jupyterlab_git/tests/test_diff.py, jupyterlab_git/tests/test_status.py
This should fix: https://github.com/jupyterlab/jupyterlab-git/issues/578 as the only non-numeric characters expected should be hyphens (https://git-scm.com/docs/git-log#Documentation/git-log.txt---numstat)
> Similar to --stat, but shows number of added and deleted lines in decimal notation and pathname without abbreviation, to make it more machine friendly. For binary files, outputs two - instead of saying 0 0.
I also added trailing `\x00` to input for tests to accurately reflect what  `git ___ -z` outputs, as well as added a binary file test case to detailed log.
Finally I cleaned up the double definition of `line_iterable` in status
=> Allow binary files in detailed log + update tests

src/components/NewBranchDialog.tsx
In the new branch dialog that you get from hitting the New Branch button the ordering does not always put the current branch first when using Firefox. This is because the comparison function would sort different depending on which argument the current branch was:
```typescript
comparator('current', 'other branch') => 'current', 'other branch'
comparator('other branch', 'current') => 'other branch', 'current'
```
Per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description this leaves the sorting order undefined (seems that chrome handles this differently than firefox). This result in the current branch not always being sorted to be first:
**Firefox**:
Which does not seem to the the intention of this code: …
=> fix branch ordering on firefox

jupyterlab_git/git.py, jupyterlab_git/tests/test_execute.py
This adds locking before executing commands. While this may add locking in some cases that are not a race (i.e. things that do not need to acquire index.lock), this solves issues related to using this with a git directory on NFS.
=> Fix race condition issues on slower FS

src/style/BranchMenu.ts, src/style/HistorySideBarStyle.ts
fixes: https://github.com/jupyterlab/jupyterlab-git/issues/590
**Original**:
**This PR**:
=> use overflow: 'auto' for historywrapper and branchmenuwrapper

src/components/NewBranchDialog.tsx
closes: https://github.com/jupyterlab/jupyterlab-git/issues/595
The order in the new branch dialog will now be:
- Current branch (if different from master)
- master (if it exists)
- rest of branches
=> sort master branch to be second in the new branch dialog

src/gitMenuCommands.ts, src/index.ts, src/widgets/gitClone.tsx
I added the the clone command to the git menu:
If `init` is in this menu then I think it makes sense to also include `clone`. Also, making `clone` available as a command will make it easier to incorporate a clone button to the updated not in repo panel.
=> add clone to commands and to git menu

jupyterlab_git/git.py, jupyterlab_git/tests/test_branch.py, jupyterlab_git/tests/test_clone.py, jupyterlab_git/tests/test_config.py, jupyterlab_git/tests/test_detailed_log.py, jupyterlab_git/tests/test_diff.py, jupyterlab_git/tests/test_handlers.py, jupyterlab_git/tests/test_pushpull.py, jupyterlab_git/tests/test_status.py, jupyterlab_git/tests/testutils.py, src/components/FileList.tsx, src/components/SinglePastCommitInfo.tsx, src/components/diff/Diff.tsx, src/components/diff/DiffWidget.tsx, src/components/diff/PlainTextDiff.tsx, src/tokens.ts, tests/GitExtension.spec.tsx, tests/test-components/Diff.spec.tsx, tests/test-components/FileItem.spec.tsx
This fixes #585. 
In addition:
- an attribute `is_binary` is sent back to the frontend from the *status* and *detailed log* requests. That attribute is used to restore showing or hiding diff icon.
- the codemirror mode is properly handled to use syntax highlighting in plain text diff widget.
=> Fix staging diff

src/components/GitPanel.tsx, src/index.ts, src/style/GitPanel.ts, src/widgets/GitWidget.tsx, tests/test-components/GitPanel.spec.tsx
Closes: https://github.com/jupyterlab/jupyterlab-git/issues/589
New UI:
I think this still needs some work on where to put and how to style the file path. The two big issues are:
1. If you are in the jupyter root directory the file path looks weird:
I didn't see an easy way to get the absolute file path from the filebrowser in order to get the folder name in this case.
2. A really long folder name renders poorly
I briefly explored the suggestion of replacing the Current Repository header with the name of the current repo but didn't see a super easy way to do this. 
Maybe just don't list the name of the current folder. i.e. say: "You aren't currently in a git repository you can either ...."
Or: style the filepath text differently and limit its length.
I also found that sometimes the …
=> Init button

src/components/BranchMenu.tsx, src/components/FileList.tsx, src/components/NewBranchDialog.tsx, src/style/NewBranchDialog.ts
close: https://github.com/jupyterlab/jupyterlab-git/issues/617
I added styling to the Discard dialog and the switching branch error dialog to make the filenames more visually distinct from the rest of the text. I also modified the text of a git checkout error to something that is hopefully clearer to beginners. In particular I followed the convention already used of saying "switch" instead of "checkout" and I added discarding the changes as an option for resolving the conflict.
**New:**
**Old:**
=> improve error dialogs

package.json
Prettier configuration is done through file .prettierrc and .prettierignore.
This should be removed.
=> Duplicate prettier configuration

src/components/CommitBox.tsx
fix: https://github.com/jupyterlab/jupyterlab-git/issues/640
Add some conditional logic to choosing the title of the commit button so it is clear to users why it is disabled.
=> Use title to describe why commit button is disabled

src/components/FileItem.tsx, src/components/FileList.tsx, src/components/GitPanel.tsx, src/tokens.ts, src/utils.ts, tests/test-components/FileList.spec.tsx
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/627
As discussed in the issue if you have both staged and unstaged changes to a file:
then the file will only show in the Staged Files list in jupyterlab-git. 
I added another option to the Status token that accounts for this state and modified the FileList and FileItem accordingly. Note how the same file appears in both Staged and Unstaged lists with different status codes, and these give different results for the diff.
When you select one instance of the file both list items are selected. I can't decide if this is a feature or a bug. But it seems that this didn't affected any of the context menu commands that depend on tracking which file is selected.
In simple staging mode it reduces to showing the diff from WORKING to HEAD:
=> show both staged and unstaged changes for a file

README.md
From discussion here https://gitter.im/jupyterlab/jupyterlab?at=5ee6abf324a3382d5d68b2ae I think that this extension should use install instead of link as it is not a core package
> I think it may be a mistake that the cookiecutter uses link. For most extension authoring, you should use jupyter labextension install. The link functionality is for times when you need to run JupyterLab itself from source or if you are working on an extension that should be in the core set of packages. I hope that helps!
=> Use install instead of link in dev instructions

binder/environment.yml, binder/postBuild
Thanks for this extension!
This adds [nbgitpuller](https://github.com/jupyterhub/nbgitpuller) to the demo binder. With the [generator](https://jupyterhub.github.io/nbgitpuller/link?tab=binder&repo=https://github.com/bollwyvl/jupyterlab-git&branch=add-nbgitpuller), this is can be an interesting way to make links that try out this repo with other repos-of interest, like this, which [brings in JupyterLab master](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-git/add-nbgitpuller?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fjupyterlab%252Fjupyterlab%26urlpath%3Dlab%252Ftree%252Ftree%252FREADME%252Fmd%26branch%3Dmaster).
My ulterior motive here is to demonstrate some behavior at the interplay between these two pieces, namely that the pull button sometimes doesn't work out of the …
=> add nbgitpuller to binder

src/components/Toolbar.tsx, src/gitMenuCommands.ts, src/index.ts, src/tokens.ts, tests/test-components/Toolbar.spec.tsx
Fixes https://github.com/jupyterlab/jupyterlab-git/issues/456
Not in a git repo:
In a git repo:
=> Clean up git menu

src/components/Toolbar.tsx
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/674
Prevents the extension crashing when navigating away from a repo when the branch menu is open. I think the branchmenu was always being rendered even when not in a repo.
@kgryte could you review?
=> check if in repo before rendering branch menu

.travis.yml, jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_branch.py, jupyterlab_git/tests/test_handlers.py
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/686
- Used an extra git command to allow for `/`s in both the branch and remote names
- tried to bring the returning of errors more in line with the rest of the extension
- Returned more info from the functions in `git.py` to allow the handlers/frontend to deal with rewriting the error messages as necessary.
I changed what is returned by `get_upstream_branch` but this is not used anywhere else in the extension so this shouldn't be a problem.
=> FIx pushing when there are slashes in branch names or in remote name

.github/workflows/publish.yml, ROADMAP.md, release.py
@telamonian I propose this PR to ease the release; i.e. it will release each time a GitHub release is published (and a git tag will be also created) - the version of npm and Python are tested to avoid publishing non-matching packages.
=> Ease release through Github workflow

jupyterlab_git/tests/test_ignore.py, src/model.ts
Add unit tests for the ignore feature #705
=> Add unit tests for ignore feature

jupyterlab_git/git.py, jupyterlab_git/tests/test_diff.py, src/index.ts, src/model.ts, src/tokens.ts, tests/GitExtension.spec.tsx
Close: https://github.com/jupyterlab/jupyterlab-git/issues/668
If any files are open in jupyterlab that are modified by:
- reset to commit
- revert commit
- switch branch
- discard changes
then they will be updated to reflect the new contents. Unless they have unsaved changes, in which case the open document will not be modified.
Use the `changed_files` command to get the list of files changed by a git command and then revert those files if they are opened.
I didn't just loop over all open documents for two reasons:
1. I didn't think of doing that that until I started writing this just now
2. (Post hoc) This is is more parsimonious - if there are large notebooks that are unaffected by the Git command then it may be slow to reload them
I updated the tests to mock the `changed_files` …
=> Update open files when Git commands modify them

jupyterlab_git/__init__.py, jupyterlab_git/git.py, jupyterlab_git/tests/test_init.py
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/584
This adds the ability for users to set a custom class to take actions. As of now, we only have a post_init action, but this can be trivially extended to give more power to end users who have non-generic needs.
Example `~/.jupyter/jupyter_notebook_config.json`:
```
"JupyterLabGitConfig": {
"custom_git_actions_class": "org.dir.MyClass"
}
```
=> Custom actions

src/components/FileList.tsx
=> Add ignore action to context menu for simple staging

binder/postBuild, src/commandsAndMenu.ts, src/components/FileList.tsx, src/model.ts, src/tokens.ts
fixes: https://github.com/jupyterlab/jupyterlab-git/issues/758
This makes sure that the displayed gitignore file is up to date without running the risk of overwriting unsaved changes in open notebooks.
=> don't use docmanager reload when opening gitignore

jupyterlab_git/git.py, jupyterlab_git/tests/test_handlers.py
This fixes the display of text diff in history for two cases:
- First commit (no previous commit)
- Commit at which the file is deleted
=> Fix text diff for 1st commit and deleted files

src/style/FileListStyle.ts, src/utils.ts
Fixes #771.  FYI, the current pattern in jupterlab is to [get the style directly from DocumentRegistry.IFileType](https://github.com/jupyterlab/jupyterlab/blob/f06c41601b45724ef40963217c575546b6f8bac2/packages/filebrowser/src/listing.ts#L1900-L1902), roughly:
```typescript
const registry: DocumentRegistry;
let fileType: DocumentRegistry.IFileType = registry.getFileTypeForModel(item);
fileType = fileType || DocumentRegistry.getDefaultTextFileType(translator);
const { icon, name } = fileType;   # note iconClass exists but is empty
```
adopting such an approach would prevent disparities between the icons shown in the file browser those in the Git panel.
- for example, [the PDF icon](https://github.com/jupyterlab/jupyterlab/blob/46908b566e84d2f025db509f0591b9d86522e796/packages/docregistry/src …
=> Restore R icon in the file list

jupyterlab_git/handlers.py, src/model.ts
Follow up #764 
The new error NotInRepository was not handled when not in a Git repository.
=> Handle not in repository error when we are not in a repository

jupyterlab_git/handlers.py, package.json, src/components/BranchMenu.tsx, src/components/FileItem.tsx, src/components/FileList.tsx, src/components/GitStage.tsx, src/components/NewBranchDialog.tsx, src/components/SinglePastCommitInfo.tsx, src/style/BranchMenu.ts, src/style/FileItemStyle.ts, src/style/FileListStyle.ts, src/style/NewBranchDialog.ts, src/style/PastCommitNode.ts, tests/test-components/BranchMenu.spec.tsx, tests/test-components/FileItem.spec.tsx, yarn.lock
Use a virtual component to display files list.
Fixes #667 
Closes #703 
Closes #704
TODO
=> Virtualized files list

src/components/NewBranchDialog.tsx
As of yesterday the new default branch on Github will be called `main` ([ref](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)). This means that a sizeable number of new repos will have `main` as the default branch when people copy-paste the github new repo instructions:
To account for that this PR adds the `main` branch to special cases when sorting branches in the newBranchDialog. The sorting order will now be:
1. `current branch`
2. `master` (if exists)
3. `main` (if exists)
4. other
=> sort main branch in NewBranchDialog

src/components/FileItem.tsx, src/components/FilePath.tsx, src/components/GitStage.tsx, src/style/SinglePastCommitInfo.ts, style/diff-nb.css
Fixes #793 
Got the scrolling weird effect to disappear by switching to pure div elements rather than ul/li for changed files list.
=> Style issues with SVG icons

src/components/GitStage.tsx, src/model.ts
Fixes #660 by ensuring `_currentMarker` is never `null`.
=> Display blank when simpleStaging is enabled

src/commandsAndMenu.tsx, src/components/FileList.tsx
Closes: https://github.com/jupyterlab/jupyterlab-git/issues/687
Made a new command for this so we can present a warning dialog. Using the `docmanager:delete-file` command directly doesn't allow for a warning dialog.
=> add context menu option to delete untracked files

src/components/FileList.tsx
If there are modifications (files in the staged group), when clicking the button undo (i.e. remove modification), the group is collapsed because the click event is propagated.
This corrects it.
=> Stop action click propagation on GitStage header

src/model.ts
Previously when discarding all changed files it was never checked what the names of the changed files were. This meant that open editors were not updated when the files changes. As well this led to a bug where options was referred to even when undefined.
Now we check for the changed files before doing the checkout to all us to pick up the changes in the case of discard all, and will fall back to querying the list of currently modified files if the `body` has no filename or branch name.
Closes: https://github.com/jupyterlab/jupyterlab-git/issues/823
attn: @lresende
=> check for changed files when discarding all changes

src/model.ts
Checking out a new branch will never cause files to change so we don't need to to check changed files. The attempt to check was failing because we were asking for the git diff between the current branch and one that did not yet exist
Fixes: https://github.com/jupyterlab/jupyterlab-git/issues/828
=> don't check for changed files when checking out a new branch

binder/postBuild
This is not really a fix for #839 But more a patch to ensure binder does not validate a docker image that is not built correctly.
=> Check extension in binder build process

jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_handlers.py
Discussed: #842
Proposal to avoid long 500 error messages in terminal when current working directory in Jupyter Lab is not a git repository:
```
[E 20:39:53.188 LabApp] 500 POST /git/show_top_level?1607891993159 (127.0.0.1) 23.65ms referer=https://127.0.0.1:8888/lab?
```
Instead, print a message to terminal (`self.log.info`) of the git command and of the error message:
```
[I 21:54:40.644 LabApp] [jupyterlab_git] Failed to execute 'git' command: git rev-parse --show-toplevel, with message: fatal: not a git repository (or any of the parent directories): .git
```
Cheers
=> Avoid 500 error messages when current working directory in Jupyter Lab is not a git repo

package.json
Bump to beta.2 to publish a beta version with #863 to reduce trouble with JupyterHub installation.
=> Bump to beta.2

src/components/GitPanel.tsx
=> Force change the repository to a current one

schema/plugin.json, src/commandsAndMenu.tsx, src/components/CommitBox.tsx, src/components/GitPanel.tsx, tests/test-components/CommitBox.spec.tsx
Fixes #773
Also:
- replaces deprecated `which` with `key`. Some browsers already dropped `which` (see the big red box on [MDN]( https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which)
- Remove incorrect  `@param event - event object` from `_onCommitClick` documentation
- Use appropriate type for `_onSummaryKeyPress` `event` argument
=> Allow to commit with ctrl + enter

src/commandsAndMenu.tsx, src/components/CommitBox.tsx, src/components/FileList.tsx, src/components/GitPanel.tsx, src/components/SinglePastCommitInfo.tsx, src/components/Toolbar.tsx, src/index.ts, src/model.ts, src/tokens.ts, src/widgets/gitClone.tsx, tests/commands.spec.tsx, tests/test-components/CommitBox.spec.tsx, tests/test-components/Toolbar.spec.tsx
Fixes #774
Changes:
- for context commands (as distinct from other commands): `ContextCommandIDs`
- for context commands' arguments (as those were already being cast in type-unsafe way and I needed to change them all): `CommandArguments`
The Git panel context menu got icons (updated):
=> Implement Git context menu in the file browser

README.md
Even if the package is installed, it does not work unless it is in the uninstalled packages list. It is caused by a bug in jupyterlab according to this issue https://github.com/jupyterlab/jupyterlab/issues/8122
=> Update README.md:Git panel is not visible

README.md
It seems to have been accidentally removed in https://github.com/jupyterlab/jupyterlab-git/pull/818
=> Restore preview gif

src/style/Toolbar.ts
Reusing `ActionButton` in https://github.com/jupyterlab/pull-requests shows that the CSS class was reloaded for `ActionButton`. That results in style override for the toolbar buttons.
=> Ensure button styles for toolbar are applied

README.md
At this moment, jupyterlab 2.x and 3.x has slight different build process. Jupyterlab 3.x version source code does not work at build time with build commands of jupyterlab 2.x. To install jupyterlab 2.x on local, while cloning repo, contributor has to ensure the branch of the jupyterlab git to be jlab-2. This change request has very minor change to add branch name while cloning the repository for building & installing locally.
=> Update README.md for installing project locally from source code

jupyterlab_git/handlers.py
- Address #958 
- `pytest jupyterlab_git`, verified all tests pass
=> Prevent empty JSON body from causing None error in git config endpoint

src/index.ts
Refreshes the file browser when the HEAD of the git repository change.
Fixes #950
=> Refresh file browser on `HEAD` change (#950)

jupyterlab_git/git.py, src/components/GitPanel.tsx, src/components/Toolbar.tsx, src/model.ts
Fixes #960
This correct the execute git command to return a code and the traceback when unexpected error occurred.
This correct the repository path setter when the server root is a git repository
=> Correct repository as root case

src/components/CommitBox.tsx, src/components/GitPanel.tsx, tests/test-components/CommitBox.spec.tsx, tests/test-components/GitPanel.spec.tsx
When switching to the history tab, the commit description and summary are not erased.
When the commit fails (ex: pre-commit checks), the commit description and summary are not erased.
Fixes #931 
Fixes #836
=> Preserve commit message when switching to the History tab (#931) (#836)

README.md
As an result of #993 I wrote a section for the Readme, to help new users setting up their SSH connection correctly in order to use the jupyterlab-git extension in connection with remotely hosted repositories.
=> Readme: Authentication to remote repo

src/components/Toolbar.tsx
Restore displaying the repository name if the repository is the Jupyter Server root folder using PageConfig. And use the information to build the local path if possible in the title.
Fixes #992
cc @bbo2adwuff is it addressing your question?
=> Use PageConfig info if git repository is the root folder

jest.config.js, package.json, schema/plugin.json, src/commandsAndMenu.tsx, src/components/diff/NotebookDiff.ts, src/components/diff/mergeview.ts, src/index.ts, yarn.lock
Allow menu and context menu customization
=> Update to JLab 3.1

package.json, src/commandsAndMenu.tsx, src/index.ts, src/widgets/GitWidget.tsx
=> Revert using default browser

src/style/CommitBox.ts
PR request based on @fcollonval's suggestion from this thread: https://github.com/jupyterlab/jupyterlab-git/issues/1035#issuecomment-919755588
=> Fix pointer on CommitBox not displaying

src/components/FileList.tsx, src/components/GitPanel.tsx
The list is handled in a similar fashion than unmerged files
Hidden if no files in that state
Listed on top to be highlighted
=> Display remotely changed files conditionaly and at the top

schema/plugin.json, src/commandsAndMenu.tsx, src/components/FileList.tsx, src/model.ts, src/tokens.ts, src/widgets/discardAllChanges.ts
This changes introduces a `Pull from remote (Discard all)` option to the Git Menu
Closes #860 
---
This may lead into the enhancement of #998, specifically
> where all pulls completely overwrote (and pruned) local files
=> Add 'Discard All and Pull' button

src/cloneCommand.ts, src/commandsAndMenu.tsx, src/components/GitPanel.tsx, src/index.ts, tests/plugin.spec.ts
The current clone dialog has a simplified interface which does not allow useful features e.g., specifying a directory where to clone the repo, post-clone actions e.g., option for opening README of the repo when it is cloned etc.
A short term solution is to isolate the clone command and expose it in a separate plugin. This will allow other extension developers to replace the command with their own implementation by disabling the command plugin and registering a new plugin with the same command id.
=> Moved clone command to plugin for extensibility

src/components/CommitBox.tsx, src/components/GitPanel.tsx, src/components/WarningBox.tsx, src/model.ts, src/style/CommitBox.ts, src/tokens.ts, tests/test-components/CommitBox.spec.tsx, tests/test-components/GitPanel.spec.tsx, tests/utils.ts
Show a notice box warning the user to pay attention to unsaved changes as he/she/they are working on files that are staged. In other words, this PR makes JupyterLab-Git shows a warning box in the commit box section when it detects unsaved changes on files that have been staged. This will potentially fix #853.
**Note: We're only checking dirty state of staged files (not other files even if they belong to the repo) and the warning box only shows up when the user is working with unsaved staged files belonging to a repo recognized by JupyterLab-Git.**
In `src/model.ts`, these are added:
- `_hasDirtyStagedFiles: boolean` indicating whether there are dirty files that are also staged files.
- `_dirtyStagedFilesStatusChanged: Signal<IGitExtension, boolean>`  that emits a signal when …
=> Warn the user of unsaved changes when working with staged files

src/model.ts
Currently doing a pull does not update the contents of open files
like switching branches does.
This runs the same function to update files as switching branches but instead of diffing the branches it diffs the previous top commit to the new HEAD. 
Fixes #1086
=> Refresh open file on pull

schema/plugin.json, src/commandsAndMenu.tsx, src/tokens.ts, src/widgets/GitResetToRemoteForm.tsx, tests/commands.spec.tsx
Add `Reset to Remote` feature to the (Git) extension's main menu, which can be executed when working with a Git repository. This lets the user reset the current branch to its remote tracking branch by performing a **hard** reset. This PR should resolve #1074, or should _help_ resolve #998.
1. A new command entry `git:reset-to-remote` is added in `src/commandsAndMenu.tsx`, `src/tokens.ts` and `schema/plugin.json`.
2. The logic for this command is overall similar to other destructive commands (e.g., forced `git:pull`). The user will be prompted for confirmation, and when it is confirmed, `GitExtension.resetToCommit(remote_tracking_branch_name)` will be invoked, which ultimately triggers a `git reset --hard <remote_tracking_branch_name>` and brings (the state of) the current branch to (the …
=> Add "Reset to Remote" feature

src/components/BranchMenu.tsx, src/components/GitPanel.tsx, src/model.ts, src/tokens.ts, tests/test-components/GitPanel.spec.tsx
=> Branch list is not updated after a branch is deleted

jupyterlab_git/__init__.py, jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_clone.py, jupyterlab_git/tests/test_fetch.py, jupyterlab_git/tests/test_handlers.py, jupyterlab_git/tests/test_pushpull.py, src/commandsAndMenu.tsx, src/components/StatusWidget.tsx, src/model.ts, src/style/StatusWidget.ts, src/tokens.ts, src/widgets/CredentialsBox.tsx, style/base.css, style/credentials-box.css
This PR fixes #659 by implementing the ability that lets JupyterLab-Git users *cache* their login credentials. By default, the information is saved temporarily for 1 hour, and this can be configured (the unit of time is *seconds*). This feature is readily available for any one of the following Git operations:
- Clone: tick the checkbox when prompted for Git credentials.
- Push: tick the checkbox when prompted for Git credentials.
- Pull: tick the checkbox when prompted for Git credentials.
- Fetch: when credentials/login information is required, a small notification dot will appear on top of the Git icon in the status bar. Users can click it for the prompt to show up, and within that prompt pop-up, tick the checkbox if they wish to have their credentials cached.
Within the cache period, …
=> Add the ability to save `Git` login temporarily

src/components/GitPanel.tsx, ui-tests/tests/commit-diff.spec.ts
=> Display diff between any two commits for a single file

src/commandsAndMenu.tsx
@fcollonval 
Implemented closing of diff window when the changes to file are discarded, but I copied a lot of codes from the gitFileDiff command
Fixes https://github.com/jupyterlab/jupyterlab-git/issues/911
---
Edited to link the issue
=> close diff window when changes to file are discarded

src/components/StatusWidget.tsx, src/index.ts, src/style/StatusWidget.ts, style/base.css, style/status-widget.css
Fixes https://github.com/jupyterlab/jupyterlab-git/issues/1100
@fcollonval 
Added current branch name on the status bar
I managed to style it but I'm not sure how to center the text vertically.
I should make the parent element a flex box and do align-item: center but I don't know how to select the parent class.
Also I'm not sure how to change the padding of the git icon so that the text could be closer to the icon.
Another issue is when navigate to another repo (change file directory), the branch name stays unless you click on the git extension icon on the left menu bar, which is a bit weird. 
---
Edited to link the related issue.
=> add current branch name on status bar

schema/plugin.json, src/commandsAndMenu.tsx, src/components/diff/NotebookDiff.ts, src/components/diff/PlainTextDiff.ts, src/tokens.ts
=> Add 'open file' command to context menu on diff tab

README.md, conftest.py, jupyterlab_git/__init__.py, jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_handlers.py
Resolves jupyterlab/jupyterlab-git#1162
=> Add configuration to exclude paths

package.json
We are breaking semver from this version on because I want to keep the previous convention of JupyterLab v3 -> git extension 0.30.0 <= x < 0.40.0.
For JupyterLab v4, we should move to 1.0.0
=> Bumping to 0.39.2

src/cancelledError.ts, src/commandsAndMenu.tsx
Provides a fix for https://github.com/jupyterlab/jupyterlab-git/issues/889
Push/Pull cancellation behaviour After Changes:
=> Return without an error message when user cancels a push/pull

jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_clone.py, src/widgets/GitCloneForm.ts
Resolves #1187
- Add an optional `submodules` bolean argument to `Git.clone()` to append `--recurse-submodules` flag (default `False`)
- Add `test_git_submodules_success` test
- Add `data["submodules"]` to `GitCloneHandler`
- Add a new submodules checkbox in `GitCloneForm` (checked by default)
- Renamed `checkbox` input to `download` in `GitCloneForm`
The clone dialog looks like this:
---
Edited to add a new clone dialog image
=> Add submodules clone checkbox

package.json
:warning: This is changing the previous rules
JLab 2 <-> git extension 0.2#.#
JLab 3 <-> git extension 0.3#.#
But it was not a great idea and I prefer to follow semver.
So 0.40.0 will be compatible with JupyterLab 3 (and only 3 as some changes will be required for JLab 4).
=> Bump to 0.40.0

src/commandsAndMenu.tsx
When a repo is created with the backtick character around it and Initialized as a repo and then opened in Terminal, the linux command is resolved or executed on a running instance. For example if a folder with the name "whoami" is created, initialized as a repo and then opened in terminal using 'Open Git repository in Terminal' you will see that whoami is resolved to the current user which is a vector of command injection.
=> Update commandsAndMenu.tsx to replace "`" in file path for Open Git Repository since it leads to Command Injection Vulnerability

src/components/GitCommitGraph.tsx, src/model.ts
Provides fix for #1088 
Freshly initialized repository after changes:
=> fix history panel not rendering when history is empty

src/components/Toolbar.tsx, src/model.ts, src/tokens.ts, tests/utils.ts
Provides fix for #995 
If the repository is in detached head (for example after switching to a tag), then switching to a branch will no longer fail. Behaviour after changes:
https://user-images.githubusercontent.com/70033855/217340638-7ebe001e-f713-44dc-bcb4-65dc2c3bfced.mov
Transforms the fake branch name (HEAD detached at #####) to ##### using Regex.
=> fix switch from a detached head to a branch not working

src/cloneCommand.ts, src/commandsAndMenu.tsx, src/git.ts, src/tokens.ts, src/widgets/CredentialsBox.tsx, yarn.lock
This fixes #1176.
**Description of Changes**
- Check to see if the remote URI matches the GitHub expression
- Change the password placeholder text accordingly
**Git Push**
https://user-images.githubusercontent.com/94336773/219996988-e0dad60f-6e51-4e74-bfd3-6cfa22731d83.mov
**Git Clone**
https://user-images.githubusercontent.com/94336773/219996946-b3ecbd35-16a2-454e-b697-338f463d9555.mov
**Git Pull**
https://user-images.githubusercontent.com/94336773/220784704-a0246d05-3c29-48e2-a32c-a8a61d657980.mov
Collaborated with @basokant on this!
=> bug: modified password placeholder text depending if remote URI is github (Fix #1176)

.github/workflows/publish-release.yml
Using the trusted publisher workflow for PyPI and npm are now available in the releaser: https://github.com/jupyter-server/jupyter_releaser/pull/511
=> Switch back to using the Jupyter Releaser actions

jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_branch.py, jupyterlab_git/tests/test_status.py, src/__tests__/test-components/GitPanel.spec.tsx, src/commandsAndMenu.tsx, src/components/BranchMenu.tsx, src/components/BranchPicker.tsx, src/components/GitPanel.tsx, src/components/GitStash.tsx, src/components/RebaseAction.tsx, src/components/StatusWidget.tsx, src/components/Toolbar.tsx, src/index.ts, src/model.ts, src/style/FileListStyle.ts, src/style/GitStashStyle.ts, src/style/RebaseActionStyle.ts, src/tokens.ts, ui-tests/tests/merge-conflict.spec.ts, ui-tests/tests/rebase.spec.ts
This PR
- fixes #1217
- fixes #1242
by
- adding support for rebase:
- The status of a repository gain a `state` to notify if a repo is in detached head, merge, cherry-pick or rebase state
- In case a rebase is in progress, the commit box is replaced by a group button that by default allow to continue (after resolving the conflicts) or optionally skip or abort the rebase.
- some styling improvement
- fix checking out from a detached head to another ref
=> Add support for rebase

jupyterlab_git/git.py, jupyterlab_git/handlers.py, jupyterlab_git/tests/test_tag.py, src/__tests__/test-components/HistorySideBar.spec.tsx, src/__tests__/test-components/PastCommitNode.spec.tsx, src/__tests__/test-components/TagMenu.spec.tsx, src/components/GitPanel.tsx, src/components/HistorySideBar.tsx, src/components/NewTagDialog.tsx, src/components/PastCommitNode.tsx, src/components/TagMenu.tsx, src/components/Toolbar.tsx, src/model.ts, src/tokens.ts
In the history panel, show the tags (if they exist) next to the commits they are pointing to. 
For this, the implementation of an `ITag` interface was required, such that for each tag we keep not only its name, but also the id of the commit it points to. 
```
export interface ITag {
name: string;
baseCommitId?: string;
}
```
=> Show tags in history sidebar

src/commandsAndMenu.tsx, src/components/HistorySideBar.tsx, src/components/NewTagDialog.tsx, src/components/PastCommitNode.tsx, src/components/TagMenu.tsx, src/tokens.ts, ui-tests/tests/add-tag.spec.ts
Created a context menu for the commits showing inside the HistorySidebar and added a new command `Add Tag`. 
Users can now right click on a commit and use the `Add Tag` command to directly create a tag pointing to that specific commit. Once clicking on the command, the `NewTagDialogBox` pops up, showing only the selected commit. 
[Screencast-Add-Tag-from-Context-Menu.webm](https://github.com/jupyterlab/jupyterlab-git/assets/91504950/b38fd172-7910-4f27-b2a1-11b930b85d91)
=> Add context menu on commits in the HistorySidebar with add tag command

src/cloneCommand.tsx, src/commandsAndMenu.tsx, src/index.ts
Drop drive from path before passing it to the git extension.
Fixes #1282
> Using the extension with a drive that is not a physical drive will still fail as git commands won't run on it.
=> Remove drive from path.

src/components/CommitBox.tsx, src/components/CommitMessage.tsx, src/components/RebaseAction.tsx, src/components/WarningBox.tsx, src/style/CommitBox.ts, src/style/GitPanel.ts
=> Fix styling

jupyterlab_git/git.py, jupyterlab_git/handlers.py, schema/plugin.json, src/commandsAndMenu.tsx, src/git.ts, src/model.ts, src/tokens.ts, style/diff-common.css
-Throws a 403 if the user tries to open a .gitignore file but the file is hidden
-Displays a helpful message showing how to enable hidden files
-Adds checkbox to not show helpful message in the feature
-Allow user to open, view and edit the .gitignore file
Temporary fix for the opening the .gitignore file in #1168
=> Load gitignore file

jupyterlab_git/git.py, jupyterlab_git/handlers.py, schema/plugin.json, src/__tests__/commands.spec.tsx, src/commandsAndMenu.tsx, src/components/diff/PreviewMainAreaWidget.ts, src/index.ts, src/model.ts, src/style/ActionButtonStyle.ts, src/style/FileItemStyle.ts, src/style/GitStageStyle.ts, src/tokens.ts, style/base.css
=> Load gitignore file (#1273)

CHANGELOG.md, src/style/GitStageStyle.ts, src/style/GitStashStyle.ts
Fixes #1296
Adds:
- `overflow-y: hidden` to hide scrollbars
- `height: 16px` to prevent jitter in Staged/Changed/Untracked
- `align-self: flex-start` to prevent jitter in Stash
| Before | After |
|--|--|
| ![before](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/f4276720-9812-4b37-bfad-da0b62b9238f) | ![after](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/ee9334b7-56c6-47aa-9a2c-3091834a392e) |
=> Fix jitter in git panel

src/__tests__/test-components/GitPanel.spec.tsx
Fixes #1325
All credit goes to @jzhang20133! 
Just opening this PR separately from #1324 to decouple the efforts of fixing unit tests vs. fixing the bug reported there.
=> Fix GitPanel unit tests

src/__tests__/test-components/GitPanel.spec.tsx, src/components/GitPanel.tsx
Fixes https://github.com/jupyterlab/jupyterlab-git/issues/1323
=> Unable to set email/username on a remote server

src/components/GitPanel.tsx
Fix for #1353. Adds a check for the validity of the `lastAuthor` information, and if the information isn't valid the author form is displayed again.
=> Confirm identity validity

.github/workflows/build.yml
Trying to fix the failing `check-links` by ignoring https://fellowship.mlh.io/ for now.
=> Add link to ignore

jupyterlab_git/git.py, jupyterlab_git/handlers.py
Fix for #1354
The issue was caused because in the command for creating a new branch `git checkout -b <branch_name> <start_point>`, git tries to resolve `<start_point>` to a commit hash, but there isn't one until a commit is made, so I added an empty commit to the `init` endpoint.
=> Create new branch in new repo

src/components/Toolbar.tsx
Fix for #1356.
Adds a boolean to check if a refresh is currently in progress and disable the refresh button if so.
=> Disable refresh button while refresh is in progress

src/__tests__/test-components/Toolbar.spec.tsx, src/components/Toolbar.tsx
This addresses the issue mentioned in https://github.com/jupyterlab/jupyterlab-git/issues/286#issuecomment-2406107190 by updating how the `Toolbar` checks for remotes.
=> Enable push/pull buttons for empty repos

src/components/BranchMenu.tsx
Addresses #1352. 
Based on @jtpio's suggestion I added a confirmation dialog when checking out a remote branch that could potentially cause a loss of changes on a users local branch.
=> Add confirmation dialog when checking out remote branch

jupyterlab_git/git.py, jupyterlab_git/tests/test_diff.py
This PR addresses #1318 by treating the parameters as Git objects and not files (e.g., [Double Hyphens in Git Diff](https://vincenttam.github.io/blog/2014/08/07/double-hyphens-in-git-diff/)). 
I'm happy to provide some tests to ensure the correctness of the functionality (testing it manually works, though).
However, the test base contains a lot of mocks. It would be awesome if you could point out some tests that actually rely on the created Git repositories and the underlying files.
=> Fix switching branches by adding double dash separator
